"""
Example MCP Server for Manim Video Generation

This is an example MCP server that can be used with the chatbot.
Configure it in streamlit_backend_complete.py to enable Manim video generation.
"""

import os
import subprocess
import glob
import re
from mcp.server.fastmcp import FastMCP
# # globals

mcp = FastMCP("ManimServer")

# Base directory for outputs
BASE_DIR = os.path.join(os.getcwd(), "manim_outputs")
os.makedirs(BASE_DIR, exist_ok=True)


@mcp.tool()
def create_video_with_narration(manim_code: str, narration_text: str, output_name: str = "final") -> str:
    """
    Create a Manim animation video with voiceover narration.
    
    This tool generates mathematical animations using Manim and adds text-to-speech narration.
    
    Args:
        manim_code: Python code for Manim animation (must contain a Scene class)
        narration_text: Text to be converted to speech and added as narration
        output_name: Name for the output file (default: "final")
    
    Returns:
        Success message with file path or error message
    
    Example:
        User: "Create a video showing a circle transforming into a square"
        The LLM will generate appropriate Manim code and narration text.
    """
    try:
        # 1. Manim Generation
        tmpdir = os.path.join(BASE_DIR, "manim_tmp")
        os.makedirs(tmpdir, exist_ok=True)
        script_path = os.path.join(tmpdir, "scene.py")
        
        # Clean the code
        clean_code = manim_code.replace("\\n", "\n").replace("\\t", "\t").strip().strip("`")
        if clean_code.startswith("python\n"):
            clean_code = clean_code[7:]
        
        # Write scene file
        with open(script_path, "w") as f:
            f.write(clean_code)
        
        # Extract scene class name
        match = re.search(r"class\s+(\w+)\(Scene\):", clean_code)
        scene = match.group(1) if match else "Demo"

        print(f"[MANIM] Generating Scene: {scene}")
        
        # Run Manim
        subprocess.run(
            ["manim", "-ql", "--media_dir", tmpdir, script_path, scene],
            capture_output=True,
            check=True
        )
        
        # Find generated video
        video_files = glob.glob(os.path.join(tmpdir, "videos", "**", f"{scene}.mp4"), recursive=True)
        video_files = [v for v in video_files if "partial_movie_files" not in v]
        
        if not video_files:
            return "ERROR: No video file generated by Manim"
        
        video_path = video_files[0]
        print(f"[MANIM] Video generated: {video_path}")

        # 2. Audio Generation
        try:
            from gtts import gTTS
            audio_path = os.path.join(BASE_DIR, f"{output_name}.mp3")
            gTTS(text=narration_text, lang='en').save(audio_path)
            print(f"[AUDIO] Audio generated: {audio_path}")
        except ImportError:
            return f"SUCCESS: Video created at {video_path} (No audio - gtts not installed)"

        # 3. Merge Video and Audio
        final_output = os.path.join(BASE_DIR, f"{output_name}_final.mp4")
        
        cmd = [
            "ffmpeg", "-y",
            "-fflags", "+genpts",
            "-i", video_path,
            "-i", audio_path,
            "-c:v", "libx264",
            "-c:a", "aac",
            "-map", "0:v:0",
            "-map", "1:a:0",
            "-pix_fmt", "yuv420p",
            "-shortest",
            final_output
        ]

        result = subprocess.run(cmd, capture_output=True, text=True)
        
        if result.returncode != 0:
            return f"ERROR during FFmpeg: {result.stderr}"

        print(f"[MERGE] Final video: {final_output}")
        return f"SUCCESS: Video created at {final_output}"
        
    except subprocess.CalledProcessError as e:
        return f"ERROR: Manim execution failed: {e.stderr.decode() if e.stderr else str(e)}"
    except Exception as e:
        return f"ERROR: {str(e)}"


@mcp.tool()
def create_simple_manim_video(manim_code: str, output_name: str = "output") -> str:
    """
    Create a simple Manim animation video without narration.
    
    Use this for quick mathematical animations without voiceover.
    
    Args:
        manim_code: Python code for Manim animation (must contain a Scene class)
        output_name: Name for the output file (default: "output")
    
    Returns:
        Success message with file path or error message
    """
    try:
        tmpdir = os.path.join(BASE_DIR, "manim_tmp")
        os.makedirs(tmpdir, exist_ok=True)
        script_path = os.path.join(tmpdir, "scene.py")
        
        # Clean the code
        clean_code = manim_code.replace("\\n", "\n").replace("\\t", "\t").strip().strip("`")
        if clean_code.startswith("python\n"):
            clean_code = clean_code[7:]
        
        # Write scene file
        with open(script_path, "w") as f:
            f.write(clean_code)
        
        # Extract scene class name
        match = re.search(r"class\s+(\w+)\(Scene\):", clean_code)
        scene = match.group(1) if match else "Demo"

        print(f"[MANIM] Generating Scene: {scene}")
        
        # Run Manim with higher quality
        subprocess.run(
            ["manim", "-qh", "--media_dir", tmpdir, script_path, scene],
            capture_output=True,
            check=True
        )
        
        # Find generated video
        video_files = glob.glob(os.path.join(tmpdir, "videos", "**", f"{scene}.mp4"), recursive=True)
        video_files = [v for v in video_files if "partial_movie_files" not in v]
        
        if not video_files:
            return "ERROR: No video file generated by Manim"
        
        video_path = video_files[0]
        
        # Copy to output location
        final_output = os.path.join(BASE_DIR, f"{output_name}.mp4")
        import shutil
        shutil.copy(video_path, final_output)
        
        return f"SUCCESS: Video created at {final_output}"
        
    except subprocess.CalledProcessError as e:
        return f"ERROR: Manim execution failed: {e.stderr.decode() if e.stderr else str(e)}"
    except Exception as e:
        return f"ERROR: {str(e)}"


if __name__ == "__main__":
    print("[MCP SERVER] Starting Manim server...")
    print(f"[MCP SERVER] Output directory: {BASE_DIR}")
    mcp.run(transport="stdio")